### ISSUE TITLE
When editing text, backslash shouldbe recognized as path (or word) separator

### ISSUE THREAD

**Issue by LewisR** [altsan/qe-text-editor#5]
When editing text which includes a URI, Ctrl-Right or Ctrl-Left will move from one part of the path to another. However, when editing text which includes a DOS, Windows, or OS/2 filesystem path which uses backslashes as directory separators, these are skipped, and the entire path (unless a dot is encountered) is treated as a single word. This makes editing batch files somewhat cumbersome.

**Comment by altsan** [comment]
This logic is handled by Qt. It is apparently fixed in Qt 5.3.1 (https://bugreports.qt.io/browse/QTBUG-40384) but not in Qt4.7.3.

There is no practical way to fix this at the application level. See: https://stackoverflow.com/questions/2545681/ (the suggested approach of using QTextEngine only applies to Qt 4.8 or later).
